### ISSUE TITLE
link to nitro enclave broken

### ISSUE THREAD

**Issue by geoffcline** [awsdocs/aws-certificate-user-guide#11]
https://docs.aws.amazon.com/acm/latest/userguide/acm-services.html#acm-nitro-enclave

The link to "nitro enclave" at the top of the page is broken. It should link to a definition of nitro enclave. 

```
Note
Public ACM certificates can be installed on Amazon EC2 instances that are connected to a Nitro Enclave, but not to other Amazon EC2 instances. 
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
