### ISSUE TITLE
Notification destination when automatic verification fails

### ISSUE THREAD

**Issue by fnobuyu** [awsdocs/aws-certificate-user-guide#18]
I think that the recipient who is notified when automatic validation fails is to the root user email address, but the documentation says notify to domain owner.

I think the owner of a domain may change over a period of time. Therefore, I think that it is easier to understand if the notification destination is clearly described. (e.i root user email address)

https://docs.aws.amazon.com/acm/latest/userguide/dns-renewal-validation.html

> If ACM cannot automatically validate a domain name, it notifies the domain owner that manual action is needed to validate the domain and complete certificate renewal.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
