### ISSUE TITLE
Need to retrieves the private key for public certificates

### ISSUE THREAD

**Issue by prakash-thales** [awsdocs/aws-certificate-user-guide#19]
**Requirement -** Any API exist to get private key for public certificate as the public certificate is created by a client 

Export certificate does the same, but only for private certificate - https://docs.aws.amazon.com/acm/latest/userguide/sdk-export.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
