### ISSUE TITLE
More complete documentation for AWS_ACM_RENEWAL_STATE_CHANGE events

### ISSUE THREAD

**Issue by blimmer** [awsdocs/aws-certificate-user-guide#20]
It would be nice to have more complete documentation (e.g., a full sample event) for the various `AWS_ACM_RENEWAL_STATE_CHANGE` events.

AWS Support provided me with these sample EventBridge events:

### ACM PCA (private) renewal

```json
{
  "source": ["aws.health"],
  "detail-type": ["AWS Health Event"],
  "detail": {
    "service": ["ACM"],
    "eventTypeCategory": ["scheduledChange"],
    "eventTypeCode": ["AWS_ACM_RENEWAL_STATE_CHANGE"],
    "eventDescription": {
      "latestDescription": [{
        "prefix": "AWS Certificate Manager (ACM) has completed the renewal"
      }]
    }
  }
}
```

### ACM renewal

```json
{
  "source": ["aws.health"],
  "detail-type": ["AWS Health Event"],
  "detail": {
    "service": ["ACM"],
    "eventTypeCategory": ["scheduledChange"],
    "eventTypeCode": ["AWS_ACM_RENEWAL_STATE_CHANGE"],
    "eventDescription": {
      "latestDescription": [{
        "prefix": "This is to notify you that AWS Certificate Manager (ACM) has completed the renewal"
      }]
    }
  }
}
```

Note that the difference is super subtle (in the description only).

Having these events fully documented (e.g., sample events for every variation of `AWS_ACM_RENEWAL_STATE_CHANGE`) would be helpful so we could be more confident using them.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
