### ISSUE TITLE
Code Samples Wanted

### ISSUE THREAD

**Issue by joneps** [awsdocs/aws-certificate-user-guide#4]
If you have any code samples that you think would improve the ACM User Guide, please let me know! 
Submit a pull request as explained in these directions: https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/CONTRIBUTING.md .

**Comment by seinecle** [comment]
Hi! Newbie here! I repeatedly try to create a CAA record but it always fails. Help?

![image](https://user-images.githubusercontent.com/1244100/72205935-c1cf3400-3488-11ea-8aa3-f1eb832f8006.png)
